#!/usr/bin/env bash
# lib/export.sh - Export and reporting functionality
# Export usage data in various formats

[[ -n "${BURNRATE_EXPORT_LOADED:-}" ]] && return 0
readonly BURNRATE_EXPORT_LOADED=1

# Source dependencies
LIB_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$LIB_DIR/core.sh"
source "$LIB_DIR/config.sh"
source "$LIB_DIR/stats.sh"
source "$LIB_DIR/pricing.sh"
source "$LIB_DIR/historical.sh"
source "$LIB_DIR/budget.sh"

# ============================================================================
# Export Formats
# ============================================================================

# Export current usage summary as JSON
export_summary_json() {
    local breakdown
    breakdown=$(get_usage_breakdown "$CONFIG_STATS_FILE")

    echo "$breakdown"
}

# Export current usage summary as CSV
export_summary_csv() {
    local breakdown
    breakdown=$(get_usage_breakdown "$CONFIG_STATS_FILE")

    # Extract values
    local model input output cache_write cache_read total_tokens
    local input_cost output_cost cache_write_cost cache_read_cost total_cost
    local cache_efficiency

    model=$(echo "$breakdown" | grep '"model"' | cut -d'"' -f4)
    input=$(echo "$breakdown" | grep '"input"' | head -1 | grep -o '[0-9]*')
    output=$(echo "$breakdown" | grep '"output"' | head -1 | grep -o '[0-9]*')
    cache_write=$(echo "$breakdown" | grep '"cache_write"' | head -1 | grep -o '[0-9]*')
    cache_read=$(echo "$breakdown" | grep '"cache_read"' | head -1 | grep -o '[0-9]*')

    # Extract costs
    local costs_section
    costs_section=$(echo "$breakdown" | sed -n '/"costs":/,/}/p')
    input_cost=$(echo "$costs_section" | grep '"input"' | grep -o '[0-9.]*')
    output_cost=$(echo "$costs_section" | grep '"output"' | grep -o '[0-9.]*')
    cache_write_cost=$(echo "$costs_section" | grep '"cache_write"' | grep -o '[0-9.]*')
    cache_read_cost=$(echo "$costs_section" | grep '"cache_read"' | grep -o '[0-9.]*')
    total_cost=$(echo "$costs_section" | grep '"total"' | grep -o '[0-9.]*')

    cache_efficiency=$(get_cache_efficiency "$CONFIG_STATS_FILE")

    # CSV output
    echo "type,tokens,cost"
    echo "Input,$input,$input_cost"
    echo "Output,$output,$output_cost"
    echo "Cache Write,$cache_write,$cache_write_cost"
    echo "Cache Read,$cache_read,$cache_read_cost"
    echo "Total,$((input + output + cache_write + cache_read)),$total_cost"
    echo ""
    echo "Cache Efficiency,$cache_efficiency%"
}

# Export current usage summary as Markdown
export_summary_markdown() {
    local breakdown
    breakdown=$(get_usage_breakdown "$CONFIG_STATS_FILE")

    # Extract values
    local model input output cache_write cache_read
    local input_cost output_cost cache_write_cost cache_read_cost total_cost
    local cache_efficiency

    model=$(echo "$breakdown" | grep '"model_friendly"' | cut -d'"' -f4)
    input=$(echo "$breakdown" | grep '"input"' | head -1 | grep -o '[0-9]*')
    output=$(echo "$breakdown" | grep '"output"' | head -1 | grep -o '[0-9]*')
    cache_write=$(echo "$breakdown" | grep '"cache_write"' | head -1 | grep -o '[0-9]*')
    cache_read=$(echo "$breakdown" | grep '"cache_read"' | head -1 | grep -o '[0-9]*')

    # Extract costs
    local costs_section
    costs_section=$(echo "$breakdown" | sed -n '/"costs":/,/}/p')
    input_cost=$(echo "$costs_section" | grep '"input"' | grep -o '[0-9.]*')
    output_cost=$(echo "$costs_section" | grep '"output"' | grep -o '[0-9.]*')
    cache_write_cost=$(echo "$costs_section" | grep '"cache_write"' | grep -o '[0-9.]*')
    cache_read_cost=$(echo "$costs_section" | grep '"cache_read"' | grep -o '[0-9.]*')
    total_cost=$(echo "$costs_section" | grep '"total"' | grep -o '[0-9.]*')

    cache_efficiency=$(get_cache_efficiency "$CONFIG_STATS_FILE")

    # Markdown output
    cat <<EOF
# Claude Token Usage Report

**Model:** $model
**Generated:** $(date '+%Y-%m-%d %H:%M:%S')

## Token Usage

| Type | Tokens | Cost |
|------|--------|------|
| Input | $(printf "%'d" "$input" 2>/dev/null || echo "$input") | \$$input_cost |
| Output | $(printf "%'d" "$output" 2>/dev/null || echo "$output") | \$$output_cost |
| Cache Write | $(printf "%'d" "$cache_write" 2>/dev/null || echo "$cache_write") | \$$cache_write_cost |
| Cache Read | $(printf "%'d" "$cache_read" 2>/dev/null || echo "$cache_read") | \$$cache_read_cost |
| **Total** | **$(printf "%'d" "$((input + output + cache_write + cache_read))" 2>/dev/null || echo "$((input + output + cache_write + cache_read))")** | **\$$total_cost** |

## Cache Performance

**Cache Efficiency:** $cache_efficiency%

---
*Generated by burnrate - Zero tokens used*
EOF
}

# ============================================================================
# Historical Exports
# ============================================================================

# Export historical data as JSON
export_history_json() {
    local start_date="${1:-}"
    local end_date="${2:-$(date +%Y-%m-%d)}"

    echo "["
    local first=true

    local breakdown
    breakdown=$(get_daily_breakdown)

    while IFS='|' read -r date model tokens cost; do
        # Filter by date range if specified
        if [[ -n "$start_date" ]]; then
            [[ "$date" < "$start_date" ]] && continue
        fi
        [[ "$date" > "$end_date" ]] && continue

        [[ "$first" == "false" ]] && echo ","
        first=false

        cat <<EOF
  {
    "date": "$date",
    "model": "$model",
    "tokens": $tokens,
    "cost": $cost
  }
EOF
    done <<< "$breakdown"

    echo "]"
}

# Export historical data as CSV
export_history_csv() {
    local start_date="${1:-}"
    local end_date="${2:-$(date +%Y-%m-%d)}"

    echo "date,model,tokens,cost"

    local breakdown
    breakdown=$(get_daily_breakdown)

    while IFS='|' read -r date model tokens cost; do
        # Filter by date range if specified
        if [[ -n "$start_date" ]]; then
            [[ "$date" < "$start_date" ]] && continue
        fi
        [[ "$date" > "$end_date" ]] && continue

        echo "$date,$model,$tokens,$cost"
    done <<< "$breakdown"
}

# Export historical data as Markdown
export_history_markdown() {
    local start_date="${1:-}"
    local end_date="${2:-$(date +%Y-%m-%d)}"

    cat <<EOF
# Claude Token Usage History

**Period:** ${start_date:-All time} to $end_date
**Generated:** $(date '+%Y-%m-%d %H:%M:%S')

## Daily Usage

| Date | Model | Tokens | Cost |
|------|-------|--------|------|
EOF

    local breakdown
    breakdown=$(get_daily_breakdown)

    while IFS='|' read -r date model tokens cost; do
        # Filter by date range if specified
        if [[ -n "$start_date" ]]; then
            [[ "$date" < "$start_date" ]] && continue
        fi
        [[ "$date" > "$end_date" ]] && continue

        local short_model
        short_model=$(echo "$model" | sed 's/claude-//; s/-20[0-9]*$//')

        echo "| $date | $short_model | $(printf "%'d" "$tokens" 2>/dev/null || echo "$tokens") | \$$cost |"
    done <<< "$breakdown"

    echo ""
    echo "---"
    echo "*Generated by burnrate - Zero tokens used*"
}

# ============================================================================
# Budget Exports
# ============================================================================

# Export budget status as JSON
export_budget_json() {
    local daily_status monthly_status
    daily_status=$(get_budget_status "daily")
    monthly_status=$(get_budget_status "monthly")

    read -r daily_pct daily_spent daily_budget <<< "$daily_status"
    read -r monthly_pct monthly_spent monthly_budget <<< "$monthly_status"

    cat <<EOF
{
  "daily": {
    "spent": $daily_spent,
    "budget": $daily_budget,
    "percentage": $daily_pct,
    "alert_threshold": ${CONFIG_BUDGET_ALERT}
  },
  "monthly": {
    "spent": $monthly_spent,
    "budget": $monthly_budget,
    "percentage": $monthly_pct,
    "alert_threshold": ${CONFIG_BUDGET_ALERT}
  },
  "generated_at": "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
}
EOF
}

# Export budget status as CSV
export_budget_csv() {
    local daily_status monthly_status
    daily_status=$(get_budget_status "daily")
    monthly_status=$(get_budget_status "monthly")

    read -r daily_pct daily_spent daily_budget <<< "$daily_status"
    read -r monthly_pct monthly_spent monthly_budget <<< "$monthly_status"

    echo "period,spent,budget,percentage"
    echo "Daily,$daily_spent,$daily_budget,$daily_pct"
    echo "Monthly,$monthly_spent,$monthly_budget,$monthly_pct"
}

# Export budget status as Markdown
export_budget_markdown() {
    local daily_status monthly_status
    daily_status=$(get_budget_status "daily")
    monthly_status=$(get_budget_status "monthly")

    read -r daily_pct daily_spent daily_budget <<< "$daily_status"
    read -r monthly_pct monthly_spent monthly_budget <<< "$monthly_status"

    cat <<EOF
# Claude Budget Status

**Generated:** $(date '+%Y-%m-%d %H:%M:%S')

## Current Period

| Period | Spent | Budget | Used |
|--------|-------|--------|------|
| Daily | \$$daily_spent | \$$daily_budget | $daily_pct% |
| Monthly | \$$monthly_spent | \$$monthly_budget | $monthly_pct% |

**Alert Threshold:** ${CONFIG_BUDGET_ALERT}%

---
*Generated by burnrate - Zero tokens used*
EOF
}

# ============================================================================
# Full Report
# ============================================================================

# Generate comprehensive report
export_full_report() {
    local format="${1:-markdown}"
    local output_file="${2:-}"

    local content=""

    case "$format" in
        json)
            content=$(cat <<JSONEOF
{
  "summary": $(export_summary_json),
  "history": $(export_history_json),
  "budget": $(export_budget_json)
}
JSONEOF
)
            ;;

        csv)
            content=$(cat <<CSVEOF
# Summary
$(export_summary_csv)

# History
$(export_history_csv)

# Budget
$(export_budget_csv)
CSVEOF
)
            ;;

        markdown|md)
            content=$(cat <<MDEOF
$(export_summary_markdown)

---

$(export_history_markdown)

---

$(export_budget_markdown)
MDEOF
)
            ;;

        *)
            log_error "Unknown format: $format"
            return 1
            ;;
    esac

    if [[ -n "$output_file" ]]; then
        echo "$content" > "$output_file"
        echo "Report saved to: $output_file"
    else
        echo "$content"
    fi
}

# ============================================================================
# Export Commands
# ============================================================================

# Export wrapper function
export_data() {
    local data_type="${1:-summary}"  # summary, history, budget, full
    local format="${2:-json}"         # json, csv, markdown
    local output_file="${3:-}"        # optional output file
    local start_date="${4:-}"         # for history
    local end_date="${5:-}"           # for history

    local content=""

    case "$data_type" in
        summary)
            case "$format" in
                json) content=$(export_summary_json) ;;
                csv) content=$(export_summary_csv) ;;
                markdown|md) content=$(export_summary_markdown) ;;
                *) log_error "Unknown format: $format"; return 1 ;;
            esac
            ;;

        history)
            case "$format" in
                json) content=$(export_history_json "$start_date" "$end_date") ;;
                csv) content=$(export_history_csv "$start_date" "$end_date") ;;
                markdown|md) content=$(export_history_markdown "$start_date" "$end_date") ;;
                *) log_error "Unknown format: $format"; return 1 ;;
            esac
            ;;

        budget)
            case "$format" in
                json) content=$(export_budget_json) ;;
                csv) content=$(export_budget_csv) ;;
                markdown|md) content=$(export_budget_markdown) ;;
                *) log_error "Unknown format: $format"; return 1 ;;
            esac
            ;;

        full)
            content=$(export_full_report "$format" "")
            ;;

        *)
            log_error "Unknown data type: $data_type"
            return 1
            ;;
    esac

    if [[ -n "$output_file" ]]; then
        echo "$content" > "$output_file"
        echo "Exported $data_type to: $output_file"
    else
        echo "$content"
    fi
}

log_debug "Export functionality loaded"
